apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.14.0
        ports:
        - containerPort: 9898
        resources:
          requests:
            cpu: "2"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 9898
  selector:
    app: podinfo
