apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: podinfo-vpa
  namespace: default
  annotations:
    # This is the magic annotation that coordinates VPA & HPA in GKE
    gke.io/autoscaling-hpa-rightsizing-mode: "gke-hpa-rightsizing-mode-policy"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu"]
        minAllowed:
          cpu: "50m"
        maxAllowed:
          cpu: "300m" # Restricted ceiling forces a tight rightsized baseline instantly, allowing load to cross HPA 50% target
